#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
  npm.cmd run eslint:fix && git add .
else
  npm run eslint:fix && git add .
fi
